### PR TITLE
BCD 3.1.1 release notes

### PR DESCRIPTION
**Pull request by tnguyen1**

### CODE REVIEW

**Comment by tnguyen1** [comment]
retest this please

**Comment by tnguyen1** [comment]
retest this please

**Comment by tnguyen1** [comment]
retest this please

**Comment by tnguyen1** [comment]
retest this please

**Comment by JeremJR** [comment]
@tnguyen1 maybe that we should update to 7.9 https://github.com/bonitasoft/bonita-continuous-delivery-doc/blob/release_3.1.1/scripts/variables.json#L3

**Review by JeremJR — APPROVED** [review]

**Pull request merged**
