### PR TITLE
add new images and official logo

### PR DESCRIPTION
**Pull request by philippelaumay**
add new images and official logo

### CODE REVIEW

**Comment by tnguyen1** [comment]
add to whitelist

**Comment by tnguyen1** [comment]
Am I wrong or these images are used nowhere in the documentation ?

**Comment by tbouffard** [comment]
@philippebonita we may also avoid image name with spaces that can cause issues. One of the commited image has that kind of name: `Bonita controller and stack.png`

**Comment by tnguyen1** [comment]
@philippebonita Can you please report this change https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/15/files to this PR - Then close PR #15 - Thanks

**Pull request closed without merging**
