### PR TITLE
fix(la-build): document custom theme build along with release 3.2.0

### PR DESCRIPTION
**Pull request by tnguyen1**

### CODE REVIEW

**Comment by laurentleseigneur** [comment]
successfully tested with docker image preview and updated pom theme settings.

**Review by laurentleseigneur — APPROVED** [review]
nice work! thanks

**Comment by tnguyen1** [comment]
retest this please

**Comment by tnguyen1** [comment]
retest this please

**Comment by tnguyen1** [comment]
retest this please

**Pull request merged**
